modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/PickleTweaks/issues"
    modId="pickletweaks"
    version="${file.jarVersion}"
    displayName="Pickle Tweaks"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/pickle-tweaks"
    # logoFile="examplemod.png"
    credits="Cavemanrockx"
    authors="BlakeBr0"
    description='''
    A bunch of vanilla+ features and tweaks.
    '''

    [[dependencies.pickletweaks]]
        modId="forge"
        mandatory=true
        versionRange="[38.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.pickletweaks]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.18,1.19)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.pickletweaks]]
        modId="cucumber"
        mandatory=true
        versionRange="[5.0.0,)"
        ordering="NONE"
        side="BOTH"